import NavMenu from "@/components/nav-menu/nav-menu";
import SessionProvider from "@/components/session-provider/session-provider";
import { getServerSession } from "next-auth";
import "./globals.css";

export const metadata = {
  title: "Create Your Events with Ease",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <NavMenu />
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
